Implemented FileParser class, added AutoValue builder for Region class, updated tests, added smaller smaps-dump file for testing.
googleinterns/smaps-visualizer pull request #4
Opened 2020-06-10 12:45 UTC by sophbohr22

2020-06-10 13:58 UTC, segfault-the-real-segfault approved these changes
Thanks for letting me review! I do love parsers.

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +      // Ensure file is a text file.
I suggest remvoing the check for the .txt extension.

.txt is just a hint; can't rely on it anyway.

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +    try {
How about making the whole body of the try{} a helper method?

Then this looks like

try {
  DoStuff(...)
} catch (ThingThatGoesWrong1 w1) {
} ...

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +          String permissions = attributes[1];
My understanding is that a java array will throw an out of bounds exception if the line isn't properly formatted?

I ask because those aren't particularly readable for a user. E.g., normally it's nice to have an error message of the form

Error on line 24 of [smaps.txt]: Unable to parse 'Rotflmao' into an address.

===
Something to think about; not clear we will necessarily invest in a bunch of nice error messages or not. Doing so is a lot of work and I think it'd be better to make progress overall. But if you get stuck and need some filler, adding this sort of thing in subsequent changes would be terrific, IMO.

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +              pathname += " " + attributes[i];
Why the " " here?

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +        if (nextRegion) {
I often leave comments in my parsers with 'example lines' that i'm trying to parse. That makes it easier for a reader to think about what attributes[3] might be, for instance.

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +          region.setStartLoc(startLoc);
How shold we reason about data integrity here?

E.g., what if startLoc > endLoc?  (which would be nonsense)

We can catch this at parse time, or write a separate validator routine?

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +          region.setPathname(pathname);
I suggest having a region.setLineNumber(int) as well.

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +        } else {
} else if (...) {

?

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +            switch (field) {
Consider making this switch statement a helper method

void fillField(String field, long value, Region.Builder builder);

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/Region.java
> +  abstract String offset();
Curious; why are accessors for numeric fields returning String?

One option:
  abstract long offset();
  abstract String formattedOffset();

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +            switch (field) {
You could also make this a property of Region.Builder

Region.Builder.setProperty(string field, string value)

Then you have a nice encapsulation of these properties inside Region (and Region.Builder),

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +    String wrongFilePathName = "../README.md";
Does this file exist when the test runs?

If it doesn't, it'd be a legal implementation to throw a fileNotFound?

2020-06-10 13:58 UTC, segfault-the-real-segfault commented on smaps/src/test/java/com/google/smaps/RegionTest.java
> +    assertEquals(512, shmemHugePages);
I suggest shortening these to:

assertEquals(512, r.shmemHugePages());

2020-06-10 14:30 UTC, maggieroemer requested changes

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> + * Takes in an smap dump text file and produces a list of the regions of that file.
Can you {@link Region} here?

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +@AutoValue
I don't think AutoValue buys us anything in this class. We really only use it for classes that act as objects like Region where they just have fields to access/change.

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +abstract class FileParser {
So this will become just a normal class (not abstract).

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +          String permissions = attributes[1];
Let's add a check of attributes size before we start accessing the different fields in this PR. And then +1 to Dan's idea of adding nice error messages down the line.

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +        } else {
Yeah can you add some comments as to what these different else/if statements are for? It's hard for me to follow.

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +    assertEquals(1072, num);
Let's figure out what ordering for assertEquals is best- i.e. assertEquals(expected, got) or assertEquals(got, expected) like you have here.

Intentionally put a wrong number instead of 1072, and see what the error message is- it should help you figure out which one should be first.
For example, if assertEquals("a", "b") fails with the message Expected "a" but got "b", then the first argument is the expected value.

2020-06-10 14:30 UTC, maggieroemer commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +    String filePathName = "../smaps-full.txt";
How long does this test take to run? We might want to just use smaps-small for testing if it takes a long time.

2020-06-10 19:34 UTC, sophbohr22 commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +    String filePathName = "../smaps-full.txt";
I don't notice a lag in running it yet, but once I add more functionality to the app I'll keep this in mind.

2020-06-10 20:09 UTC, sophbohr22 commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +    assertEquals(1072, num);
Just tested it, it's (expected, got) 👍

2020-06-10 20:15 UTC, sophbohr22 commented on smaps/src/main/java/com/google/smaps/Region.java
> +  abstract String offset();
Java has a parser that can take in hex numbers as strings and convert them to integers so I think I'm gonna use that in another class when I need to use those hex numbers.

2020-06-10 20:40 UTC, maggieroemer requested changes

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +  static void parseFile(String filePathname, List<Region> regions) throws FileNotFoundException {
this method should throws IllegalArgumentException b/c of line 70 right?

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +            // if there are extra details after pathname, append to string and add space between
Capitalize the start of the comment and add a period at the end.

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +
I would hoist the comments for the if and following else if above them but inline them where they match up.

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +  static void dataIntegrityCheck(Region r) {
I would say either leave out this method and just add a todo up above saying to add a dataIntegreityCheck, or change the signature to return a boolean and do at least one check for now (so maybe just startLoc < endLoc) with a todo to do the rest.

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/test/java/com/google/smaps/FileParserTest.java
> +  public void wrongFileFormat() {
This is totally fine for now, but we may want to move to throwing exceptions for formats that we can't handle instead of returning lists of 0. We will have to think about how we want the visualizer to react when a user uploads something incorrect. No action item here for now, just something to think about :)

2020-06-10 20:40 UTC, maggieroemer commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +      } else if (!nextRegion) {
Hmm I wonder if we can set this up as:
if (nextRegion)
else if (line.contains("VMFlags"))
else

2020-06-10 20:47 UTC, sophbohr22 commented on smaps/src/main/java/com/google/smaps/FileParser.java
> +  static void parseFile(String filePathname, List<Region> regions) throws FileNotFoundException {
If I don't have "throws FileNotFoundException" I get an error saying it must be caught (maybe because it doesn't know the method is being called inside a try catch)? But I'll add that it throws IllegalArgumentException too.

2020-06-11 13:23 UTC, maggieroemer approved these changes
LGTM! Just a small nit about a a Javadoc comment.

2020-06-11 13:23 UTC, mmanderso commented on smaps/src/main/java/com/google/smaps/FileParser.java
>   * Takes in an smap dump text file and produces a list of the regions of that file. {@link Region}
This should read:
Takes in an smaps dump text file and produces a list of the {@link Region} objects of that file.

2020-06-11 13:31 UTC, merged